//! Bundled synthetic routes for demo mode and acceptance test A05.
//! Both are clearly labelled synthetic: generated elevation, not real terrain.
//! The demo loop is placed at 0°N 0°E ("Null Island", open ocean) so it is
//! never mistaken for a real road.

use rl_domain::geo::LatLon;
use rl_domain::route::{process, synthetic, ElevationSource, ProfileConfig, RouteInput};
use rl_storage::store::{RouteRecord, Store};

pub const DEMO_ROUTE_ID: &str = "demo-null-island-loop";
pub const A05_ROUTE_ID: &str = "test-grade-steps-a05";

fn src() -> ElevationSource {
    ElevationSource { kind: "synthetic".into(), dataset: "Ridgeline synthetic generator".into(), resolution_m: 10.0, fetched_utc: 0, attribution: "Synthetic data generated by Ridgeline".into() }
}

pub fn ensure_bundled_routes(store: &Store) -> Result<(), String> {
    let defs: [(&str, &str, &str, Vec<(f64, f64)>, bool); 2] = [
        (
            DEMO_ROUTE_ID,
            "Demo: Null Island Loop (synthetic)",
            "A 12 km synthetic loop with rolling hills, one 1.2 km climb at about 6%, and descents. Elevation is generated, not real terrain.",
            vec![(1200.0, 0.0), (800.0, 2.0), (600.0, 4.0), (1200.0, 6.0), (500.0, 1.0), (900.0, -4.0), (700.0, -6.0), (1500.0, 0.5), (900.0, 3.0), (800.0, -2.5), (1100.0, -1.5), (1800.0, -2.05)],
            true,
        ),
        (
            A05_ROUTE_ID,
            "Test: Grade steps (A05, synthetic)",
            "Technical test profile: 1 km flat, 1 km at +5%, 0.5 km flat, 1 km at -3%, 0.5 km flat.",
            vec![(1000.0, 0.0), (1000.0, 5.0), (500.0, 0.0), (1000.0, -3.0), (500.0, 0.0)],
            false,
        ),
    ];
    for (id, name, desc, legs, looped) in defs {
        let existing = store.route(id)?;
        let have_profile = store.route_profile(id).ok().flatten().map(|p| p.version == rl_domain::route::PROFILE_VERSION).unwrap_or(false);
        if existing.is_some() && have_profile {
            continue;
        }
        let start = if looped { LatLon { lat: 0.0, lon: 0.0 } } else { LatLon { lat: 0.05, lon: 0.05 } };
        let segs = vec![synthetic(start, &legs, looped)];
        let rec = RouteRecord {
            schema: 1,
            id: id.into(),
            name: name.into(),
            kind: "synthetic".into(),
            description: desc.into(),
            created_utc: 0,
            segments: segs.clone(),
            elevation: src(),
            dem_segments: None,
            corrections: vec![],
            flat_fallback: false,
            waypoints: vec![],
            routing_provider: String::new(),
            attribution: String::new(),
            reversed_from: None,
            bundled: true,
        };
        let prof = process(&RouteInput { segments: &segs, source: src(), corrections: &[], flat_fallback: false }, &ProfileConfig::default())?;
        store.save_route(&rec)?;
        store.save_route_profile(id, &prof)?;
    }
    Ok(())
}
