// Generates THIRD_PARTY_NOTICES.md from `cargo metadata` (desktop crate) and
// the UI's installed production dependencies. Run by the lockfiles workflow.
//
// usage: node scripts/gen-notices.mjs <cargo-metadata.json> <ui-dir> > THIRD_PARTY_NOTICES.md
import { readFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { execSync } from "node:child_process";

const [metaPath, uiDir] = process.argv.slice(2);
const meta = JSON.parse(readFileSync(metaPath, "utf8"));
const crates = meta.packages
  .filter((p) => p.source) // skip workspace/path crates (Ridgeline's own)
  .map((p) => ({ name: p.name, version: p.version, license: p.license ?? (p.license_file ? "see license file" : "unspecified"), url: p.repository ?? p.homepage ?? `https://crates.io/crates/${p.name}` }))
  .sort((a, b) => a.name.localeCompare(b.name) || a.version.localeCompare(b.version));

// Production npm dependencies that end up in the bundled UI.
let lsOut;
try {
  lsOut = execSync("npm ls --omit=dev --all --json", { cwd: uiDir, encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] });
} catch (e) {
  lsOut = e.stdout; // npm ls exits non-zero on extraneous packages but still prints the tree
}
const tree = JSON.parse(lsOut);
const seen = new Map();
const walk = (deps) => {
  for (const [name, d] of Object.entries(deps ?? {})) {
    if (!d || d.extraneous || d.missing || !d.version) continue;
    const key = `${name}@${d.version}`;
    if (!seen.has(key)) {
      const pj = join(uiDir, "node_modules", name, "package.json");
      let license = "unspecified";
      let url = `https://www.npmjs.com/package/${name}`;
      if (existsSync(pj)) {
        const p = JSON.parse(readFileSync(pj, "utf8"));
        license = typeof p.license === "string" ? p.license : p.license?.type ?? license;
        const repo = typeof p.repository === "string" ? p.repository : p.repository?.url;
        if (repo) url = repo.replace(/^git\+/, "").replace(/\.git$/, "").replace(/^git:\/\//, "https://");
      }
      seen.set(key, { name, version: d.version, license, url });
    }
    walk(d.dependencies);
  }
};
walk(tree.dependencies);
const npm = [...seen.values()].sort((a, b) => a.name.localeCompare(b.name));

const table = (rows) => ["| Package | Version | License | Source |", "|---|---|---|---|", ...rows.map((r) => `| ${r.name} | ${r.version} | ${r.license} | ${r.url} |`)].join("\n");
const count = (rows) => {
  const c = {};
  for (const r of rows) c[r.license] = (c[r.license] ?? 0) + 1;
  return Object.entries(c)
    .sort((a, b) => b[1] - a[1])
    .map(([l, n]) => `${l} (${n})`)
    .join(", ");
};

console.log(`# Third-party notices

Ridgeline is MIT-licensed. It is built from and ships the open-source components listed below, each under its own license. This file is generated by \`scripts/gen-notices.mjs\` in CI from the lockfiles; do not edit by hand. The bundled UI also ships \`app.js.LEGAL.txt\` with the license comments retained by the bundler.

## Assets and data

| Item | License / terms |
|---|---|
| Barlow and Barlow Condensed fonts (Jeremy Tribby) | SIL Open Font License 1.1 — \`apps/desktop/ui/public/fonts/OFL-Barlow.txt\` |
| Map data shown in maps | © OpenStreetMap contributors, ODbL 1.0 (via OpenFreeMap / OpenMapTiles) |
| Routing results | Valhalla (MIT); data © OpenStreetMap contributors, ODbL 1.0 |
| Elevation | Open-Meteo.com (CC BY 4.0); Copernicus DEM GLO-90 © DLR e.V. 2010–2014 and © Airbus Defence and Space GmbH 2014–2018, provided under COPERNICUS by the European Union and ESA |
| Workouts, demo routes, icons | Original to this project (MIT) |

## Rust crates in the desktop app (${crates.length})

Licenses: ${count(crates)}.

${table(crates)}

## JavaScript packages in the bundled UI (${npm.length})

Licenses: ${count(npm)}.

${table(npm)}
`);
